# Generated by Django 2.0.3 on 2018-05-31 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0002_add_timestamp_to_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time Added'),
        ),
    ]
