# Generated by Django 2.0.3 on 2018-05-31 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0003_change_default_to_auto_now_add_in_timestamp_in_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialposturl',
            name='post',
        ),
        migrations.DeleteModel(
            name='SocialPostUrl',
        ),
    ]
