# Generated by Django 2.0.3 on 2018-05-31 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0004_remove_SocialPostUrl_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialpostattachment',
            old_name='post',
            new_name='social_post',
        ),
    ]
