# Generated by Django 2.0.3 on 2018-05-31 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0005_rename_post_to_social_post_in_SocialPostAttachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialpost',
            name='text',
            field=models.CharField(max_length=4096),
        ),
    ]
