# Generated by Django 2.0.3 on 2018-04-02 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('file', models.FileField(upload_to='attachments/')),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='BaseUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(verbose_name='Grade')),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Innovation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=1024)),
                ('assumptions', models.CharField(max_length=1024)),
                ('benefits', models.CharField(max_length=1024)),
                ('costs', models.CharField(max_length=1024)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('blocked', 'Blocked'), ('rejected', 'Rejected'), ('suspended', 'Suspended'), ('in_replenishment', 'In Replenishment'), ('pending', 'Pending')], default='pending', max_length=32)),
                ('status_substantiation', models.CharField(max_length=1024, verbose_name='Status Substantiation')),
                ('student_grade_weight', models.PositiveIntegerField(verbose_name="Student's Grade Weight")),
                ('employee_grade_weight', models.PositiveIntegerField(verbose_name="Employee's Grade Weight")),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Time Added')),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innovations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=128)),
                ('innovation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='innovations.Innovation')),
            ],
        ),
        migrations.CreateModel(
            name='InnovationAttachment',
            fields=[
                ('baseattachment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='innovations.BaseAttachment')),
                ('innovation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='innovations.Innovation')),
            ],
            options={
                'verbose_name': 'Innovation Attachment',
                'verbose_name_plural': 'Innovation Attachments',
            },
            bases=('innovations.baseattachment',),
        ),
        migrations.CreateModel(
            name='InnovationUrl',
            fields=[
                ('baseurl_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='innovations.BaseUrl')),
                ('innovation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='innovations.Innovation')),
            ],
            options={
                'verbose_name': 'Innovation Url',
                'verbose_name_plural': 'Innovation Urls',
            },
            bases=('innovations.baseurl',),
        ),
        migrations.AddField(
            model_name='grade',
            name='innovation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='innovations.Innovation'),
        ),
        migrations.AddField(
            model_name='grade',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL),
        ),
    ]
