# Generated by Django 2.0.3 on 2018-04-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovation',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('blocked', 'Blocked'), ('rejected', 'Rejected'), ('suspended', 'Suspended'), ('in_replenishment', 'In Replenishment'), ('pending', 'Pending'), ('voting', 'Voting')], default='pending', max_length=32),
        ),
    ]
