# Generated by Django 2.0.3 on 2018-05-10 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('innovations', '0002_add_voting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViolationReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substantiation', models.CharField(max_length=1024)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('closing_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('innovation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violation_reports', to='innovations.Innovation')),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violation_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
