# Generated by Django 2.0.3 on 2018-06-17 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('innovations', '0005_change_assumptions_to_textfied'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_status', models.CharField(choices=[('accepted', 'Accepted'), ('blocked', 'Blocked'), ('rejected', 'Rejected'), ('suspended', 'Suspended'), ('in_replenishment', 'In Replenishment'), ('pending', 'Pending'), ('voting', 'Voting')], max_length=32)),
                ('substantiation', models.CharField(max_length=1024, null=True, verbose_name='Status Substantiation')),
                ('innovation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_votes', to='innovations.Innovation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
