# Generated by Django 2.0.3 on 2018-06-19 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('innovations', '0006_statusvote'),
    ]

    operations = [
        migrations.CreateModel(
            name='InnovationComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=4096)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Time Added')),
                ('innovation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innovation_comment', to='innovations.Innovation')),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innovation_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
