# Generated by Django 2.0.3 on 2018-06-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovations', '0007_innovationcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovation',
            name='student_grade_weight',
            field=models.DecimalField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], decimal_places=2, default=1.0,
                                      max_digits=3, verbose_name="Student's Grade Weight"),
        ),
        migrations.AlterField(
            model_name='innovation',
            name='employee_grade_weight',
            field=models.DecimalField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], decimal_places=2, default=1.0,
                                      max_digits=3, verbose_name="Employee's Grade Weight"),
        ),
    ]
